/* Onboarding */
import {exp} from "react-native-reanimated";

export const SET_ONBOARDING_DATA = 'SET_ONBOARDING_DATA';
export const ONBOARDING_IS_LOADING = 'ONBOARDING_IS_LOADING';
export const ONBOARDING_ERROR = 'ONBOARDING_ERROR';

/* User */
export const LOGIN = 'LOGIN';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REAUTHENTICATE = 'REAUTHENTICATE';
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS';
export const REAUTHENTICATE_FAILURE = 'REAUTHENTICATE_FAILURE';

export const GET_MY_USER = 'GET_MY_USER';
export const GET_MY_USER_SUCCESS = 'GET_MY_USER_SUCCESS';
export const GET_MY_USER_FAILURE = 'GET_MY_USER_FAILURE';

export const EDIT_MY_USER = 'EDIT_MY_USER';
export const EDIT_MY_USER_SUCCESS = 'EDIT_MY_USER_SUCCESS';
export const EDIT_MY_USER_FAILURE = 'EDIT_MY_USER_FAILURE';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

/* Set Device Info */
export const SET_DEVICE_INFO = 'SET_DEVICE_INFO';

/* Register */
export const REGISTER = 'REGISTER';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTERED = 'REGISTERED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

/* Feed */
export const GET_FEEDS = 'GET_FEEDS';
export const SET_FEEDS = 'SET_FEEDS';
export const GET_FEEDS_FAILED = 'GET_FEEDS_FAILED';

export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';

export const POST_SHARED = 'POST_SHARED';

export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';

export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
export const COMMENTED_ON_POST = 'COMMENTED_ON_POST';
export const REMOVE_COMMENT_FROM_POST = 'REMOVE_COMMENT_FROM_POST';

export const GET_ALL_POST_LIKES = 'GET_ALL_POST_LIKES';
export const GET_ALL_POST_SHARES = 'GET_ALL_POST_SHARES';
export const GET_ALL_POST_COMMENTS = 'GET_ALL_POST_COMMENTS';

export const ADD_LIKES_TO_POST = 'ADD_LIKES_TO_POST';
export const ADD_SHARES_TO_POST = 'ADD_SHARES_TO_POST';
export const ADD_COMMENTS_TO_POST = 'ADD_COMMENTS_TO_POST';
export const ADD_MORE_COMMENTS_TO_POST = 'ADD_MORE_COMMENTS_TO_POST';

export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const SHARE_POST = 'SHARE_POST';

export const ADD_NEW_POST = 'ADD_NEW_POST';
export const ADD_SHARED_POST = 'ADD_SHARED_POST';
export const ADD_NEW_POST_FAILED = 'ADD_NEW_POST_FAILED';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const SET_LOAD_MORE_START = 'SET_LOAD_MORE_START';

export const GET_USER_SUGGESTION = 'GET_USER_SUGGESTION';
export const SET_USER_SUGGESTION = 'SET_USER_SUGGESTION';
export const RELOAD_USER_SUGGESTION = 'RELOAD_USER_SUGGESTION';

// Profile
export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const GET_CONVERSATION_BETWEEN_USERS = 'GET_CONVERSATION_BETWEEN_USERS';
export const SET_CONVERSATION_BETWEEN_USERS = 'SET_CONVERSATION_BETWEEN_USERS';

export const FOLLOW_USER_SUGGESTION = 'FOLLOW_USER_SUGGESTION';
export const UNFOLLOW_USER_SUGGESTION = 'UNFOLLOW_USER_SUGGESTION';

export const SET_FOLLOW_USER_SUGGESTION = 'SET_FOLLOW_USER_SUGGESTION';
export const SET_UNFOLLOW_USER_SUGGESTION = 'SET_UNFOLLOW_USER_SUGGESTION';

export const SUGGESTION_LOAD_MORE = 'SUGGESTION_LOAD_MORE';
export const GET_SUGGESTION = 'GET_SUGGESTION';

export const GET_USER_SUGGESTION_FAILED = 'GET_USER_SUGGESTION_FAILED';

/* Messages */
export const UPDATE_MESSAGE_VIEWED_STATUS = 'UPDATE_MESSAGE_VIEWED_STATUS';
export const SEND_USER_MESSAGE = 'SEND_USER_MESSAGE';
export const GET_ALL_CONVERSATIONS = 'GET_ALL_CONVERSATIONS';
export const GET_FARM_CONVERSATIONS = 'GET_FARM_CONVERSATIONS';
export const GET_CONVERSATION_BETWEEN_TWO_PEOPLE =
  'GET_CONVERSATION_BETWEEN_TWO_PEOPLE';

export const UPDATE_MESSAGE_LAST_SENT = 'UPDATE_MESSAGE_LAST_SENT';

/* Conversation */
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SET_FARM_CONVERSATIONS = 'SET_FARM_CONVERSATIONS';
export const GET_CONVERSATION_MESSAGES = 'GET_CONVERSATION_MESSAGES';
export const GET_CONVERSATION_MESSAGES_SUCCESS = 'GET_CONVERSATION_MESSAGES_SUCCESS';
export const GET_CONVERSATION_MESSAGES_FAILURE = 'GET_CONVERSATION_MESSAGES_FAILURE';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';

export const START_IMAGE_UPLOAD = 'START_IMAGE_UPLOAD';

export const SET_USER_SUGGESTION_IN_FINDPEOPLE =
  'SET_USER_SUGGESTION_IN_FINDPEOPLE';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_SINGLE_POST_FAILED = 'GET_SINGLE_POST_FAILED';
export const LIKE_SINGLE_POST = 'LIKE_SINGLE_POST';
export const LIKE_SINGLE_POST_SUCCESS = 'LIKE_SINGLE_POST_SUCCESS';
export const LIKE_SINGLE_POST_FAILED = 'LIKE_SINGLE_POST_FAILED';
export const UNLIKE_SINGLE_POST = 'UNLIKE_SINGLE_POST';
export const UNLIKE_SINGLE_POST_SUCCESS = 'UNLIKE_SINGLE_POST_SUCCESS';
export const UNLIKE_SINGLE_POST_FAILED = 'UNLIKE_SINGLE_POST_FAILED';
export const ADD_COMMENT_TO_SINGLE_POST = 'ADD_COMMENT_TO_SINGLE_POST';
export const ADD_COMMENT_TO_SINGLE_POST_SUCCESS =
  'ADD_COMMENT_TO_SINGLE_POST_SUCCESS';
export const ADD_COMMENT_TO_SINGLE_POST_FAILED =
  'ADD_COMMENT_TO_SINGLE_POST_FAILED';
export const GET_SINGLE_POST_LIKES = 'GET_SINGLE_POST_LIKES';
export const GET_SINGLE_POST_LIKES_SUCCESS = 'GET_SINGLE_POST_LIKES_SUCCESS';
export const GET_SINGLE_POST_LIKES_FAILED = 'GET_SINGLE_POST_LIKES_FAILED';
export const GET_SINGLE_POST_COMMENTS = 'GET_SINGLE_POST_COMMENTS';
export const GET_SINGLE_POST_COMMENTS_SUCCESS =
  'GET_SINGLE_POST_COMMENTS_SUCCESS';
export const GET_SINGLE_POST_COMMENTS_FAILED =
  'GET_SINGLE_POST_COMMENTS_FAILED';
export const GET_SINGLE_POST_SHARES = 'GET_SINGLE_POST_SHARES';
export const GET_SINGLE_POST_SHARES_SUCCESS = 'GET_SINGLE_POST_SHARES_SUCCESS';
export const GET_SINGLE_POST_SHARES_FAILED = 'GET_SINGLE_POST_SHARES_FAILED';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILED = 'SEARCH_USERS_FAILED';

export const SEARCH_FARMS = 'SEARCH_FARMS';
export const SEARCH_FARMS_SUCCESS = 'SEARCH_FARMS_SUCCESS';
export const SEARCH_FARMS_FAILED = 'SEARCH_FARMS_FAILED';

export const REMOVE_USERS = 'REMOVE_USERS';
export const REMOVE_FARMS = 'REMOVE_FARMS';

/* Profile */
export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

/* Farms */
export const GET_FARM = 'GET_FARM';
export const GET_FARM_SUCCESS = 'GET_FARM_SUCCESS';
export const GET_FARM_FAILURE = 'GET_FARM_FAILURE';

export const GET_FARM_CATEGORIES = 'GET_FARM_CATEGORIES';
export const GET_FARM_CATEGORIES_SUCCESS = 'GET_FARM_CATEGORIES_SUCCESS';
export const GET_FARM_CATEGORIES_FAILURE = 'GET_FARM_CATEGORIES_FAILURE';

export const GET_EDIT_FARM = 'GET_FARM';
export const GET_EDIT_FARM_SUCCESS = 'GET_FARM_SUCCESS';
export const GET_EDIT_FARM_FAILURE = 'GET_FARM_FAILURE';

export const CREATE_OR_EDIT_FARM = 'CREATE_OR_EDIT_FARM';
export const CREATE_OR_EDIT_FARM_SUCCESS = 'CREATE_OR_EDIT_FARM_SUCCESS';
export const CREATE_OR_EDIT_FARM_FAILURE = 'CREATE_OR_EDIT_FARM_FAILURE';

export const GET_CONVERSATION_WITH_FARM = 'GET_CONVERSATION_WITH_FARM';
export const GET_CONVERSATION_WITH_FARM_SUCCESS = 'GET_CONVERSATION_WITH_FARM_SUCCESS';
export const GET_CONVERSATION_WITH_FARM_FAILURE = 'GET_CONVERSATION_WITH_FARM_FAILURE';

export const SUBSCRIBE_TO_FARM = 'SUBSCRIBE_TO_FARM';
export const SUBSCRIBE_TO_FARM_SUCCESS = 'SUBSCRIBE_TO_FARM_SUCCESS';
export const SUBSCRIBE_TO_FARM_FAILURE = 'SUBSCRIBE_TO_FARM_FAILURE';

export const UNSUBSCRIBE_FROM_FARM = 'UNSUBSCRIBE_FROM_FARM';
export const UNSUBSCRIBE_FROM_FARM_SUCCESS = 'UNSUBSCRIBE_FROM_FARM_SUCCESS';
export const UNSUBSCRIBE_FROM_FARM_FAILURE = 'UNSUBSCRIBE_FROM_FARM_FAILURE';

export const GET_FARM_MEMBERS = 'GET_FARM_MEMBERS';
export const GET_FARM_MEMBERS_SUCCESS = 'GET_FARM_MEMBERS_SUCCESS';
export const GET_FARM_MEMBERS_FAILURE = 'GET_FARM_MEMBERS_FAILURE';

/* Farm Memberships */
export const REQUEST_FARM_MEMBERSHIP = 'REQUEST_FARM_MEMBERSHIP';
export const REQUEST_FARM_MEMBERSHIP_SUCCESS =
  'REQUEST_FARM_MEMBERSHIP_SUCCESS';
export const REQUEST_FARM_MEMBERSHIP_FAILURE =
  'REQUEST_FARM_MEMBERSHIP_FAILURE';

export const CANCEL_FARM_MEMBERSHIP_REQUEST = 'CANCEL_FARM_MEMBERSHIP_REQUEST';
export const CANCEL_FARM_MEMBERSHIP_REQUEST_SUCCESS =
  'CANCEL_FARM_MEMBERSHIP_REQUEST_SUCCESS';
export const CANCEL_FARM_MEMBERSHIP_REQUEST_FAILURE =
  'CANCEL_FARM_MEMBERSHIP_REQUEST_FAILURE';

export const ACCEPT_FARM_MEMBERSHIP_REQUEST = 'ACCEPT_FARM_MEMBERSHIP_REQUEST';
export const ACCEPT_FARM_MEMBERSHIP_REQUEST_SUCCESS =
  'ACCEPT_FARM_MEMBERSHIP_REQUEST_SUCCESS';
export const ACCEPT_FARM_MEMBERSHIP_REQUEST_FAILURE =
  'ACCEPT_FARM_MEMBERSHIP_REQUEST_FAILURE';

export const REJECT_FARM_MEMBERSHIP_REQUEST = 'REJECT_FARM_MEMBERSHIP_REQUEST';
export const REJECT_FARM_MEMBERSHIP_REQUEST_SUCCESS =
  'REJECT_FARM_MEMBERSHIP_REQUEST_SUCCESS';
export const REJECT_FARM_MEMBERSHIP_REQUEST_FAILURE =
  'REJECT_FARM_MEMBERSHIP_REQUEST_FAILURE';

export const DELETE_FARM_MEMBER = 'DELETE_FARM_MEMBER';
export const DELETE_FARM_MEMBER_SUCCESS = 'DELETE_FARM_MEMBER_SUCCESS';
export const DELETE_FARM_MEMBER_FAILURE = 'DELETE_FARM_MEMBER_FAILURE';
/* End Farm Memberships */
